config/routes.rb
Rails.application.routes.draw do
  resources :cotacts
  resources :notices
  resources :notices
  resources :notices
  resources :links
  resources :testimonials
  resources :events
  resources :news
  resources :sliders

end

app/models/notice.rb
class Notice < ActiveRecord::Base
	has_many :messages, :dependent=>:destroy
	accepts_nested_attributes_for :messages, :allow_destroy=>true

end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:name, :general, :dept, :year, :semister,:messages_attributes=>[:id,:body,:stype,:_destroy])
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :general %><br>
    <%= f.check_box :general %>
  </div>
  <div class="field">
    <%= f.label :dept %><br>
    <%= f.select(:dept,["Math","chem","Physics"]) %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.select(:year,["First","Second","Third","Final"] )%>
  </div>
  <div class="field">
    <%= f.label :semister %><br>
    <%= f.select(:semister,["Fall","Winter","Summer"]) %>
  </div>

<div id ="messages">
    <%= f.fields_for :messages do |task|%>
     <%= render 'message_fields', f: task%>
     <%end%>
  
    <%= link_to_add_association 'add task', f, :messages%>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notices/_message_fields.html.erb
<div class="nested-fields" >
 <div class= "field">
    <%= f.label :body %>
    <br>
    <%= f.text_area :body ,placeholder: :"comments here" %>
  <div class="field"> 
   <%= f.label :stype,"info type" %><br>  
   <%= f.radio_button(:stype,"info") %> "info"
   <%= f.radio_button(:stype,"warning") %> "warning"
   <%= f.radio_button(:stype,"success") %> "success"
   <%= f.radio_button(:stype,"danger") %> "danger"
   
   </div>
  <%= link_to_remove_association "remove task", f %>
  </div>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>General</th>
      <th>Dept</th>
      <th>Year</th>
      <th>Semister</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.name %></td>
        <td><%= notice.general %></td>
        <td><%= notice.dept %></td>
        <td><%= notice.year %></td>
        <td><%= notice.semister %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form' %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @notice.name %>
</p>

<p>
  <strong>General:</strong>
  <%= @notice.general %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @notice.dept %>
</p>

<p>
  <strong>Year:</strong>
  <%= @notice.year %>
</p>

<p>
  <strong>Semister:</strong>
  <%= @notice.semister %>
</p>
<% for msg in @notice.messages %>

<p>
<h3><%=msg.body%></h3>
<%end%>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>